# Generated by Django 5.2.6 on 2025-09-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_banner1_promoimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
